# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18j7k93Un2QceKW1j_T4EhMnZ-dDPDB9l
"""

#config.py
TRAINING_FILE = "../input/train_folds.csv"
MODEL_OUTPUT = "../models/"