# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18j7k93Un2QceKW1j_T4EhMnZ-dDPDB9l
"""

#model_dispatcher.py
from sklearn import tree
from sklearn import ensemble
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier 
models = {"decision_tree_gini": tree.DecisionTreeClassifier(
    criterion="gini"
),"decision_tree_entropy": tree.DecisionTreeClassifier(
    criterion="entropy"
),
"rf": ensemble.RandomForestClassifier(),
"mlp": MLPClassifier(),  
"svm_linear": SVC(kernel="linear"),        
"svm_poly": SVC(kernel="poly"),            
"svm_rbf": SVC(kernel="rbf"),              
"svm_sigmoid": SVC(kernel="sigmoid"),            
"naive_bayes": GaussianNB() , 
"knn": KNeighborsClassifier() 
          }